name: web_portfolio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.5
  google_fonts: ^8.1.0
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  visibility_detector: ^0.4.0+2
  flutter_earth_globe: ^2.2.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatar.jpg
    - assets/images/projects/
    - assets/images/earth_night.jpg
    - assets/images/ozi/

