name: webportfolio
version: 1.0.0+1
publish_to: none
description: A modern web portfolio built with Flutter.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.2.1
  lottie: ^3.2.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

